class FontHasklugNerdFont < Formula
  version "2.1.0"
  sha256 "73a7387e9569ab33bee5aebb62ef86762c2e77084799760e41f61250c107cb6f"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Hasklig.zip"
  desc "Hasklug Nerd Font (Hasklig)"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "Hasklug Bold Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Bold Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Medium Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug ExtraLight Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Black Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug ExtraLight Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Black Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Semibold Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Medium Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Semibold Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Light Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Light Italic Nerd Font Complete.otf"
    (share/"fonts").install "Hasklug Bold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Bold Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Medium Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug ExtraLight Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Black Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug ExtraLight Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Black Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Semibold Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Medium Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Semibold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Light Nerd Font Complete Mono.otf"
    (share/"fonts").install "Hasklug Light Italic Nerd Font Complete Mono.otf"
  end
  test do
  end
end
