class FontIosevkaNerdFont < Formula
  version "2.1.0"
  sha256 "6bd29ef886b808d1d76dd85f82b8823452265fda582801734aab6f9460270de3"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Iosevka.zip"
  desc "Iosevka Nerd Font (Iosevka)"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "Iosevka Bold Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Bold Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Heavy Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Heavy Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Heavy Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Heavy Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Thin Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Thin Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Thin Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Thin Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Bold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Bold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Bold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Bold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Light Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Light Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Light Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Light Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Bold Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Bold Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Bold Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Bold Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Medium Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Medium Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Medium Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Medium Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Extralight Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Extralight Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Extralight Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Extralight Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Medium Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Medium Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Medium Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Medium Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Extralight Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Extralight Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Extralight Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Extralight Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Heavy Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Heavy Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Heavy Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Heavy Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Thin Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Thin Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Thin Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Thin Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Thin Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Thin Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Thin Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Thin Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Medium Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Medium Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Medium Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Medium Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Extralight Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Extralight Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Extralight Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Extralight Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Heavy Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Heavy Oblique Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Heavy Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Heavy Oblique Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Light Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Light Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Light Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Light Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Light Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Light Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Light Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Light Italic Nerd Font Complete Mono.ttf"
  end
  test do
  end
end
