class FontMartianMono < Formula
  version "0.9.0"
  sha256 "2d7c4e9103b1df5551eb6d91f19122b80bb82e97aa77d7ddc65cb3edc95cd8d3"
  url "https://github.com/evilmartians/mono/releases/download/v#{version}/martian-mono-#{version}-otf.zip"
  desc "Martian Mono"
  desc "Monospaced font from Evil Martians"
  homepage "https://github.com/evilmartians/mono"
  def install
    (share/"fonts").install "MartianMono-CnBd.otf"
    (share/"fonts").install "MartianMono-CnLt.otf"
    (share/"fonts").install "MartianMono-CnMd.otf"
    (share/"fonts").install "MartianMono-CnRg.otf"
    (share/"fonts").install "MartianMono-CnTh.otf"
    (share/"fonts").install "MartianMono-CnxBd.otf"
    (share/"fonts").install "MartianMono-CnxLt.otf"
    (share/"fonts").install "MartianMono-NrBd.otf"
    (share/"fonts").install "MartianMono-NrLt.otf"
    (share/"fonts").install "MartianMono-NrMd.otf"
    (share/"fonts").install "MartianMono-NrRg.otf"
    (share/"fonts").install "MartianMono-NrTh.otf"
    (share/"fonts").install "MartianMono-NrxBd.otf"
    (share/"fonts").install "MartianMono-NrxLt.otf"
    (share/"fonts").install "MartianMono-StdBd.otf"
    (share/"fonts").install "MartianMono-StdLt.otf"
    (share/"fonts").install "MartianMono-StdMd.otf"
    (share/"fonts").install "MartianMono-StdRg.otf"
    (share/"fonts").install "MartianMono-StdTh.otf"
    (share/"fonts").install "MartianMono-StdxBd.otf"
    (share/"fonts").install "MartianMono-StdxLt.otf"
    (share/"fonts").install "MartianMono-WdBd.otf"
    (share/"fonts").install "MartianMono-WdLt.otf"
    (share/"fonts").install "MartianMono-WdMd.otf"
    (share/"fonts").install "MartianMono-WdRg.otf"
    (share/"fonts").install "MartianMono-WdTh.otf"
    (share/"fonts").install "MartianMono-WdxBd.otf"
    (share/"fonts").install "MartianMono-WdxLt.otf"
  end
  test do
  end
end
