class FontBlexMonoNerdFont < Formula
  version "2.3.3"
  sha256 "e4fcea4b03b7cf9d6792dec4379c3e876c7739dd24174f79d78e99a069ff38d4"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/IBMPlexMono.zip"
  desc "BlexMono Nerd Font (IBM Plex Mono)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "Blex Mono Bold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Bold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Bold Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono ExtraLight Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono ExtraLight Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono ExtraLight Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono ExtraLight Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Light Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Light Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Light Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Light Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Medium Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Medium Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Medium Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Medium Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono SemiBold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono SemiBold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono SemiBold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono SemiBold Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Text Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Text Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Text Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Text Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Thin Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Thin Italic Nerd Font Complete.ttf"
    (share/"fonts").install "Blex Mono Thin Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Blex Mono Thin Nerd Font Complete.ttf"
  end
  test do
  end
end
