class FontCaskaydiaMonoNerdFont < Formula
  version "3.2.1"
  sha256 "603c68495918d6fddd800ffb6ab1ae726f5e410affc6b02047b1cdb00453efab"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/CascadiaMono.zip"
  desc "CaskaydiaMono Nerd Font (Cascadia Mono)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "CaskaydiaMonoNerdFont-Bold.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-BoldItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-ExtraLight.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-ExtraLightItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-Italic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-Light.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-LightItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-Regular.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-SemiBold.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-SemiBoldItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-SemiLight.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFont-SemiLightItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-Bold.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-BoldItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-ExtraLight.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-ExtraLightItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-Italic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-Light.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-LightItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-Regular.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-SemiBold.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-SemiBoldItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-SemiLight.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontMono-SemiLightItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-Bold.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-BoldItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-ExtraLight.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-ExtraLightItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-Italic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-Light.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-LightItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-Regular.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-SemiBold.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-SemiBoldItalic.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-SemiLight.ttf"
    (share/"fonts").install "CaskaydiaMonoNerdFontPropo-SemiLightItalic.ttf"
  end
  # No zap stanza required

  test do
  end
end
