class FontPlemolJpHs < Formula
  desc "Plemoljp hs font"
  homepage "https://github.com/yuru7/PlemolJP"
  url "https://github.com/yuru7/PlemolJP/releases/download/v2.0.2/PlemolJP_HS_v2.0.2.zip"
  version "2.0.2"
  sha256 "1f309e1247609d116f5cbc2ed01b1a269b4642105798f6507fa4e09a1844483d"

  def install
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console_HS/PlemolJP35ConsoleHS-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35_HS/PlemolJP35HS-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole_HS/PlemolJPConsoleHS-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_HS/PlemolJPHS-ThinItalic.ttf")[0]
  end

  test do
    assert_path_exists share/"fonts"
  end
end
