class FontIosevkaNerdFont < Formula
  version "2.3.3"
  sha256 "526638087347705f6604afa593907a715bfb5b49247bef36e8a12e9c4543e861"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Iosevka.zip"
  desc "Iosevka Nerd Font families (Iosevka)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "Iosevka Nerd Font Complete Bold Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Bold Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Bold.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete ExtraBold Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete ExtraBold Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete ExtraBold.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete ExtraLight Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete ExtraLight Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete ExtraLight.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Heavy Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Heavy Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Heavy.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Light Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Light Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Light.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Medium Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Medium Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Medium.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Bold Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Bold Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Bold.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono ExtraBold Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono ExtraBold Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono ExtraBold.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono ExtraLight Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono ExtraLight Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono ExtraLight.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Heavy Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Heavy Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Heavy.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Light Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Light Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Light.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Medium Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Medium Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Medium.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono SemiBold Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono SemiBold Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono SemiBold.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Thin Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Thin Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono Thin.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete SemiBold Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete SemiBold Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete SemiBold.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Thin Italic.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Thin Oblique.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete Thin.ttf"
    (share/"fonts").install "Iosevka Nerd Font Complete.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Bold Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Bold Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Bold.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete ExtraBold Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete ExtraBold Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete ExtraBold.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete ExtraLight Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete ExtraLight Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete ExtraLight.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Heavy Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Heavy Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Heavy.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Light Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Light Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Light.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Medium Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Medium Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Medium.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Bold Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Bold Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Bold.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono ExtraBold Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono ExtraBold Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono ExtraBold.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono ExtraLight Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono ExtraLight Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono ExtraLight.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Heavy Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Heavy Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Heavy.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Light Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Light Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Light.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Medium Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Medium Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Medium.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono SemiBold Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono SemiBold Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono SemiBold.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Thin Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Thin Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono Thin.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete SemiBold Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete SemiBold Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete SemiBold.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Thin Italic.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Thin Oblique.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete Thin.ttf"
    (share/"fonts").install "Iosevka Term Nerd Font Complete.ttf"
  end
  test do
  end
end
