class FontUrwBase35 < Formula
  version "20170801"
  sha256 "4505042c8859166f5bff77e33907e244b66eb4e04b56646e14e0a97e5757cd21"
  url "https://github.com/ArtifexSoftware/urw-base35-fonts/archive/#{version}.zip"
  desc "URW++ base 35"
  homepage "https://github.com/ArtifexSoftware/urw-base35-fonts"
  def install
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsC059-BdIta.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsC059-Bold.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsC059-Italic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsC059-Roman.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsD050000L.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusMonoPS-Bold.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusMonoPS-BoldItalic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusMonoPS-Italic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusMonoPS-Regular.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusRoman-Bold.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusRoman-BoldItalic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusRoman-Italic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusRoman-Regular.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusSans-Bold.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusSans-BoldItalic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusSans-Italic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusSans-Regular.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusSansNarrow-BdOblique.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusSansNarrow-Bold.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusSansNarrow-Oblique.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsNimbusSansNarrow-Regular.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsP052-Bold.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsP052-BoldItalic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsP052-Italic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsP052-Roman.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsStandardSymbolsPS.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsURWBookman-Demi.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsURWBookman-DemiItalic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsURWBookman-Light.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsURWBookman-LightItalic.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsURWGothic-Book.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsURWGothic-BookOblique.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsURWGothic-Demi.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsURWGothic-DemiOblique.otf"
    (share/"fonts").install "../urw-base35-fonts-#{version}/fontsZ003-MediumItalic.otf"
  end
  test do
  end
end
