class FontNotoSansKhmer < Formula
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansKhmer-unhinted.zip", verified: "noto-website-2.storage.googleapis.com/"
  desc "Noto Sans Khmer"
  homepage "https://www.google.com/get/noto/#sans-khmr"
  def install
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmer-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansKhmerUI-Thin.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
