class FontUbuntuSansNerdFont < Formula
  version "3.2.1"
  sha256 "4d6a2ee81a394cb2af720a6046e40e1b742a3455ec47b4c987f04fa7a92a432e"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/UbuntuSans.zip"
  desc "UbuntuSans Nerd Font families (Ubuntu Sans)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFont-Bold.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFont-BoldItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFont-Italic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFont-Medium.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFont-MediumItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFont-Regular.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFont-SemiBold.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFont-SemiBoldItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontMono-Bold.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontMono-BoldItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontMono-Italic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontMono-Medium.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontMono-MediumItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontMono-Regular.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontMono-SemiBold.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontMono-SemiBoldItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontPropo-Bold.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontPropo-BoldItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontPropo-Italic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontPropo-Medium.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontPropo-MediumItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontPropo-Regular.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontPropo-SemiBold.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansMonoNerdFontPropo-SemiBoldItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFont-Bold.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFont-BoldItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFont-Italic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFont-Medium.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFont-MediumItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFont-Regular.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFont-SemiBold.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFont-SemiBoldItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFontPropo-Bold.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFontPropo-BoldItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFontPropo-Italic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFontPropo-Medium.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFontPropo-MediumItalic.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFontPropo-Regular.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFontPropo-SemiBold.ttf"
    (share/"fonts").install "ufl/ubuntusansmono/" + "UbuntuSansNerdFontPropo-SemiBoldItalic.ttf"
  end
  # No zap stanza required

  test do
  end
end
