class FontNotoSans < Formula
  version "2.013"
  sha256 "9fd595dd701d7ea103a9ba8a9cfdcf0c35c5574ef754fecabe718eadad8bccde"
  url "https://github.com/notofonts/latin-greek-cyrillic/releases/download/NotoSans-v#{version}/NotoSans-v#{version}.zip", verified: "github.com/notofonts/"
  desc "Noto Sans"
  desc "Sans-serif variable font"
  homepage "https://notofonts.github.io/"
  def install
    parent = File.dirname(Dir.pwd) != (ENV['HOMEBREW_TEMP'] || '/tmp') ?  '../' : ''
    (share/"fonts").install "#{parent}NotoSans/unhinted/variable/NotoSans-Italic[wdth,wght].ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/variable/NotoSans[wdth,wght].ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-Black.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-BlackItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-Bold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-BoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-Condensed.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedBlack.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedBlackItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedExtraBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedExtraBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedExtraLight.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedExtraLightItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedLight.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedLightItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedMedium.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedMediumItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedSemiBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedThin.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-CondensedThinItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensed.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedBlack.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedBlackItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedExtraBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedExtraBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedExtraLight.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedExtraLightItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedLight.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedLightItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedMedium.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedMediumItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedSemiBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedThin.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraCondensedThinItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraLight.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ExtraLightItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-Italic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-Light.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-LightItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-Medium.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-MediumItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-Regular.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensed.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedBlack.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedBlackItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedExtraBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedExtraBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedExtraLight.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedExtraLightItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedLight.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedLightItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedMedium.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedMediumItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedSemiBold.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedThin.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-SemiCondensedThinItalic.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-Thin.ttf"
    (share/"fonts").install "#{parent}NotoSans/unhinted/ttf/NotoSans-ThinItalic.ttf"
  end
  test do
  end
end
