class FontHubotSans < Formula
  version "1.0.1"
  sha256 "b460d36097a5c9a3e45710cbe1554589eaa5765d7c2c88df364516f3e27159b1"
  url "https://github.com/github/hubot-sans/releases/download/v#{version}/Hubot-Sans.zip"
  desc "Hubot-Sans"
  desc "Hubot Sans, a variable font from GitHub"
  homepage "https://github.com/github/hubot-sans"
  def install
    parent = File.dirname(Dir.pwd) != (ENV['HOMEBREW_TEMP'] || '/tmp') ?  '../' : ''
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-Black.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-BlackItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-Bold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-BoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-ExtraBold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-ExtraBoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-ExtraLight.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-ExtraLightItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-Italic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-Light.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-LightItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-Medium.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-MediumItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-Regular.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-SemiBold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSans-SemiBoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-Black.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-BlackItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-Bold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-BoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-ExtraBold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-ExtraBoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-ExtraLight.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-ExtraLightItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-Italic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-Light.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-LightItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-Medium.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-MediumItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-Regular.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-SemiBold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansCondensed-SemiBoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-Black.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-BlackItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-Bold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-BoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-ExtraBold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-ExtraBoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-ExtraLight.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-ExtraLightItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-Italic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-Light.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-LightItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-Medium.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-MediumItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-Regular.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-SemiBold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/HubotSansExpanded-SemiBoldItalic.otf"
  end
  # No zap stanza required

  test do
  end
end
