class FontJetbrainsMonoNerdFont < Formula
  version "2.2.2"
  sha256 "8b9b6c58081d179ecd50839a6b211dbd24b61e66d87715860129b6138982ee7b"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/JetBrainsMono.zip"
  desc "JetBrainsMono Nerd Font (JetBrains Mono)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono"
  def install
    (share/"fonts").install "JetBrains Mono Bold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Bold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Bold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono ExtraBold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono ExtraBold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono ExtraBold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono ExtraBold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono ExtraLight Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono ExtraLight Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono ExtraLight Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono ExtraLight Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Light Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Light Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Light Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Light Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Medium Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Medium Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Medium Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Medium Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Bold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Bold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Bold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraBold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraBold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraBold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraBold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraLight Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraLight Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraLight Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL ExtraLight Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Light Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Light Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Light Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Light Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Medium Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Medium Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Medium Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Medium Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Regular Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Regular Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL SemiBold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL SemiBold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL SemiBold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL SemiBold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Thin Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Thin Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono NL Thin Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono NL Thin Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Regular Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Regular Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono SemiBold Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono SemiBold Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono SemiBold Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono SemiBold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Thin Italic Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Thin Italic Nerd Font Complete Mono.ttf"
    (share/"fonts").install "JetBrains Mono Thin Nerd Font Complete.ttf"
    (share/"fonts").install "JetBrains Mono Thin Nerd Font Complete Mono.ttf"
  end
  test do
  end
end
