class FontHasklugNerdFont < Formula
  version "3.0.2"
  sha256 "e4235ca3c1adcf7f7e5756695c79c4226ae7d625e19f4827f142e2758a044317"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Hasklig.zip"
  desc "Hasklug Nerd Font (Hasklig)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "HasklugNerdFont-Black.otf"
    (share/"fonts").install "HasklugNerdFont-BlackItalic.otf"
    (share/"fonts").install "HasklugNerdFont-Bold.otf"
    (share/"fonts").install "HasklugNerdFont-BoldItalic.otf"
    (share/"fonts").install "HasklugNerdFont-ExtraLight.otf"
    (share/"fonts").install "HasklugNerdFont-ExtraLightItalic.otf"
    (share/"fonts").install "HasklugNerdFont-Italic.otf"
    (share/"fonts").install "HasklugNerdFont-Light.otf"
    (share/"fonts").install "HasklugNerdFont-LightItalic.otf"
    (share/"fonts").install "HasklugNerdFont-Medium.otf"
    (share/"fonts").install "HasklugNerdFont-MediumItalic.otf"
    (share/"fonts").install "HasklugNerdFont-Regular.otf"
    (share/"fonts").install "HasklugNerdFont-SemiBold.otf"
    (share/"fonts").install "HasklugNerdFont-SemiBoldItalic.otf"
    (share/"fonts").install "HasklugNerdFontMono-Black.otf"
    (share/"fonts").install "HasklugNerdFontMono-BlackItalic.otf"
    (share/"fonts").install "HasklugNerdFontMono-Bold.otf"
    (share/"fonts").install "HasklugNerdFontMono-BoldItalic.otf"
    (share/"fonts").install "HasklugNerdFontMono-ExtraLight.otf"
    (share/"fonts").install "HasklugNerdFontMono-ExtraLightItalic.otf"
    (share/"fonts").install "HasklugNerdFontMono-Italic.otf"
    (share/"fonts").install "HasklugNerdFontMono-Light.otf"
    (share/"fonts").install "HasklugNerdFontMono-LightItalic.otf"
    (share/"fonts").install "HasklugNerdFontMono-Medium.otf"
    (share/"fonts").install "HasklugNerdFontMono-MediumItalic.otf"
    (share/"fonts").install "HasklugNerdFontMono-Regular.otf"
    (share/"fonts").install "HasklugNerdFontMono-SemiBold.otf"
    (share/"fonts").install "HasklugNerdFontMono-SemiBoldItalic.otf"
    (share/"fonts").install "HasklugNerdFontPropo-Black.otf"
    (share/"fonts").install "HasklugNerdFontPropo-BlackItalic.otf"
    (share/"fonts").install "HasklugNerdFontPropo-Bold.otf"
    (share/"fonts").install "HasklugNerdFontPropo-BoldItalic.otf"
    (share/"fonts").install "HasklugNerdFontPropo-ExtraLight.otf"
    (share/"fonts").install "HasklugNerdFontPropo-ExtraLightItalic.otf"
    (share/"fonts").install "HasklugNerdFontPropo-Italic.otf"
    (share/"fonts").install "HasklugNerdFontPropo-Light.otf"
    (share/"fonts").install "HasklugNerdFontPropo-LightItalic.otf"
    (share/"fonts").install "HasklugNerdFontPropo-Medium.otf"
    (share/"fonts").install "HasklugNerdFontPropo-MediumItalic.otf"
    (share/"fonts").install "HasklugNerdFontPropo-Regular.otf"
    (share/"fonts").install "HasklugNerdFontPropo-SemiBold.otf"
    (share/"fonts").install "HasklugNerdFontPropo-SemiBoldItalic.otf"
  end
  # No zap stanza required

  test do
  end
end
