class FontSpectral < Formula
  head "https://github.com/productiontype/Spectral/archive/master.zip"
  desc "Spectral"
  homepage "https://github.com/productiontype/Spectral"
  def install
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-Bold.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-BoldItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-ExtraBold.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-ExtraBoldItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-ExtraLight.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-ExtraLightItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-Italic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-Light.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-LightItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-Medium.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-MediumItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-Regular.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-SemiBold.ttf"
    (share/"fonts").install "../Spectral-master/fonts/desktopSpectral-SemiBoldItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-Bold.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-BoldItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-ExtraBold.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-ExtraBoldItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-ExtraLight.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-ExtraLightItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-Italic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-Light.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-LightItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-Medium.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-MediumItalic.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-Regular.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-SemiBold.ttf"
    (share/"fonts").install "../Spectral-master/fonts/scSpectralSC-SemiBoldItalic.ttf"
  end
  test do
  end
end
