class FontNotoSansThai < Formula
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansThai-unhinted.zip", verified: "noto-website-2.storage.googleapis.com/"
  desc "Noto Sans Thai"
  homepage "https://www.google.com/get/noto/#sans-thai"
  def install
    (share/"fonts").install Dir.glob("./**/NotoSansThai-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThai-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansThaiUI-Thin.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
