class FontVollkorn < Formula
  version "4.105"
  sha256 "e650ea9d967c2af1e9b8d34e1118721728bcd73ccfd3220da4264661301e8af5"
  url "http://vollkorn-typeface.com/download/vollkorn-#{version.to_s.gsub(".", "-")}.zip"
  desc "Vollkorn"
  homepage "http://vollkorn-typeface.com/"
  def install
    (share/"fonts").install "../PS-OTFVollkorn-Black.otf"
    (share/"fonts").install "../PS-OTFVollkorn-BlackItalic.otf"
    (share/"fonts").install "../PS-OTFVollkorn-Bold.otf"
    (share/"fonts").install "../PS-OTFVollkorn-BoldItalic.otf"
    (share/"fonts").install "../PS-OTFVollkorn-ExtraBold.otf"
    (share/"fonts").install "../PS-OTFVollkorn-ExtraBoldItalic.otf"
    (share/"fonts").install "../PS-OTFVollkorn-Italic.otf"
    (share/"fonts").install "../PS-OTFVollkorn-Medium.otf"
    (share/"fonts").install "../PS-OTFVollkorn-MediumItalic.otf"
    (share/"fonts").install "../PS-OTFVollkorn-Regular.otf"
    (share/"fonts").install "../PS-OTFVollkorn-SemiBold.otf"
    (share/"fonts").install "../PS-OTFVollkorn-SemiBoldItalic.otf"
    (share/"fonts").install "TTF/Vollkorn-Black.ttf"
    (share/"fonts").install "TTF/Vollkorn-BlackItalic.ttf"
    (share/"fonts").install "TTF/Vollkorn-Bold.ttf"
    (share/"fonts").install "TTF/Vollkorn-BoldItalic.ttf"
    (share/"fonts").install "TTF/Vollkorn-ExtraBold.ttf"
    (share/"fonts").install "TTF/Vollkorn-ExtraBoldItalic.ttf"
    (share/"fonts").install "TTF/Vollkorn-Italic.ttf"
    (share/"fonts").install "TTF/Vollkorn-Medium.ttf"
    (share/"fonts").install "TTF/Vollkorn-MediumItalic.ttf"
    (share/"fonts").install "TTF/Vollkorn-Regular.ttf"
    (share/"fonts").install "TTF/Vollkorn-SemiBold.ttf"
    (share/"fonts").install "TTF/Vollkorn-SemiBoldItalic.ttf"
  end
  test do
  end
end
