class FontNotoSansDisplay < Formula
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansDisplay-unhinted.zip", verified: "noto-website-2.storage.googleapis.com/"
  desc "Noto Sans Display"
  homepage "https://www.google.com/get/noto/#sans-lgc-display"
  def install
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-BlackItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedBlackItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedExtraBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedMediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedSemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-CondensedThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedBlackItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedExtraBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedMediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedSemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraCondensedThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedBlackItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedExtraBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedMediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedSemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-SemiCondensedThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDisplay-ThinItalic.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
