class FontCoelacanth < Formula
  version "0.008"
  sha256 "77c0d55970b6275a7249bd73a9907b22e6613c1bf3a162a74a41656b1ff81139"
  url "https://github.com/Fuzzypeg/Coelacanth/raw/master/release/coelacanth_v#{version}.zip"
  desc "Coelacanth"
  desc "Serif typeface inspired by Bruce Rogers' Centaur"
  homepage "https://github.com/Fuzzypeg/Coelacanth"
  def install
    (share/"fonts").install "ofl/codystar/" + "Coelacanth.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthBold.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthCaption.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthCaptionBold.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthCaptionExtraLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthCaptionHeavy.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthCaptionIt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthCaptionLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthCaptionSemibd.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthDisplay.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthDisplayBold.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthDisplayExtraLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthDisplayHeavy.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthDisplayLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthDisplaySemibd.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthExtraLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthHeavy.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthIt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthPearl.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthPearlBold.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthPearlExtraLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthPearlHeavy.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthPearlIt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthPearlLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthPearlSemibd.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSemibd.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubcapt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubcaptBold.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubcaptExtraLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubcaptHeavy.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubcaptIt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubcaptLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubcaptSemibd.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubhd.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubhdBold.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubhdExtraLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubhdHeavy.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubhdLt.otf"
    (share/"fonts").install "ofl/codystar/" + "CoelacanthSubhdSemibd.otf"
  end
  # No zap stanza required

  test do
  end
end
