class FontRobotoMonoNerdFont < Formula
  version "3.1.1"
  sha256 "e84acfb5838ab8636c77a1a3f319e82f7466ee3911dff42be78d086bc5843988"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/RobotoMono.zip"
  desc "RobotoMono Nerd Font (Roboto Mono)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-Bold.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-BoldItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-Italic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-Light.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-LightItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-Medium.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-MediumItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-Regular.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-SemiBold.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-SemiBoldItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-Thin.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFont-ThinItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-Bold.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-BoldItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-Italic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-Light.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-LightItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-Medium.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-MediumItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-Regular.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-SemiBold.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-SemiBoldItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-Thin.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontMono-ThinItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-Bold.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-BoldItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-Italic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-Light.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-LightItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-Medium.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-MediumItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-Regular.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-SemiBold.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-SemiBoldItalic.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-Thin.ttf"
    (share/"fonts").install "RobotoMono/" + "RobotoMonoNerdFontPropo-ThinItalic.ttf"
  end
  # No zap stanza required

  test do
  end
end
