class FontLeagueMono < Formula
  version "2.300"
  sha256 "16bdc983aa5eb1803a3c2fbb11d15a8cfa1ce317334a61b01f0f3ab302fdcf0d"
  url "https://github.com/theleagueof/league-mono/releases/download/#{version}/LeagueMono-#{version}.tar.xz", verified: "github.com/theleagueof/league-mono/"
  desc "League Mono"
  desc "Monospace typeface inspired by Fira Mono, Libertinus Mono, and Courier"
  homepage "https://www.theleagueofmoveabletype.com/league-mono"
  def install
    parent = File.dirname(Dir.pwd) != (ENV['HOMEBREW_TEMP'] || '/tmp') ?  '../' : ''
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-Thin.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-UltraLight.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-Light.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-Regular.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-Medium.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-SemiBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-Bold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-ExtraBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-CondensedThin.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-CondensedUltraLight.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-CondensedLight.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-Condensed.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-CondensedMedium.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-CondensedSemiBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-CondensedBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-CondensedExtraBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-ExtendedThin.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-ExtendedUltraLight.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-ExtendedLight.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-ExtendedMedium.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-ExtendedRegular.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-ExtendedSemiBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-ExtendedBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-ExtendedExtraBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-NarrowThin.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-NarrowUltraLight.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-NarrowLight.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-NarrowMedium.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-NarrowRegular.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-NarrowSemiBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-NarrowBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-NarrowExtraBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-WideThin.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-WideUltraLight.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-WideLight.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-WideMedium.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-WideRegular.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-WideSemiBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-WideBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/static/OTF/LeagueMono-WideExtraBold.otf"
    (share/"fonts").install "#{parent}LeagueMono-#{version}/variable/TTF/LeagueMono-VF.ttf"
  end
  test do
  end
end
