class FontNotoSansTamil < Formula
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansTamil-unhinted.zip", verified: "noto-website-2.storage.googleapis.com/"
  desc "Noto Sans Tamil"
  homepage "https://www.google.com/get/noto/#sans-taml"
  def install
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamil-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansTamilUI-Thin.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
