class FontInter < Formula
  desc "Variable font designed for display"
  homepage "https://rsms.me/inter/"
  url "https://github.com/rsms/inter/releases/download/v#{version}/Inter-#{version}.zip", verified: "github.com/rsms/inter/"
  version "4.0"
  sha256 "ff970a5d4561a04f102a7cb781adbd6ac4e9b6c460914c7a101f15acb7f7d1a4"
  name "Inter"
  def install
    parent = (File.dirname(Dir.pwd) == (ENV["HOMEBREW_TEMP"] || "/tmp")) ? "" : "../"
    (share/"fonts").install "#{parent}InterVariable-Italic.ttf"
    (share/"fonts").install "#{parent}InterVariable.ttf"
    (share/"fonts").install "#{parent}extras/otf/Inter-Black.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-BlackItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-Bold.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-BoldItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-ExtraBold.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-ExtraBoldItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-ExtraLight.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-ExtraLightItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-Italic.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-Light.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-LightItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-Medium.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-MediumItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-Regular.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-SemiBold.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-SemiBoldItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-Thin.otf"
    (share/"fonts").install "#{parent}extras/otf/Inter-ThinItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-Black.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-BlackItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-Bold.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-BoldItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-ExtraBold.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-ExtraBoldItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-ExtraLight.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-ExtraLightItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-Italic.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-Light.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-LightItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-Medium.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-MediumItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-Regular.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-SemiBold.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-SemiBoldItalic.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-Thin.otf"
    (share/"fonts").install "#{parent}extras/otf/InterDisplay-ThinItalic.otf"
  end
  # No zap stanza required

  test do
  end
end
