class FontCoelacanth < Formula
  version "0.006"
  sha256 "6926eab323cc893b7f5c6115514421c7b8d96d23376c8181e8342219816f925c"
  url "https://github.com/Fuzzypeg/Coelacanth/releases/download/v#{version}/coelacanth_v#{version}.zip"
  desc "Coelacanth"
  desc "Serif typeface inspired by Bruce Rogers' Centaur"
  homepage "https://github.com/Fuzzypeg/Coelacanth"
  def install
    (share/"fonts").install "Coelacanth.otf"
    (share/"fonts").install "CoelacanthBold.otf"
    (share/"fonts").install "CoelacanthCaption.otf"
    (share/"fonts").install "CoelacanthCaptionBold.otf"
    (share/"fonts").install "CoelacanthCaptionExtraLt.otf"
    (share/"fonts").install "CoelacanthCaptionHeavy.otf"
    (share/"fonts").install "CoelacanthCaptionLt.otf"
    (share/"fonts").install "CoelacanthCaptionSemibd.otf"
    (share/"fonts").install "CoelacanthDisplay.otf"
    (share/"fonts").install "CoelacanthDisplayBold.otf"
    (share/"fonts").install "CoelacanthDisplayExtraLt.otf"
    (share/"fonts").install "CoelacanthDisplayHeavy.otf"
    (share/"fonts").install "CoelacanthDisplayLt.otf"
    (share/"fonts").install "CoelacanthDisplaySemibd.otf"
    (share/"fonts").install "CoelacanthExtraLt.otf"
    (share/"fonts").install "CoelacanthHeavy.otf"
    (share/"fonts").install "CoelacanthItalic.otf"
    (share/"fonts").install "CoelacanthLt.otf"
    (share/"fonts").install "CoelacanthPearl.otf"
    (share/"fonts").install "CoelacanthPearlBold.otf"
    (share/"fonts").install "CoelacanthPearlExtraLt.otf"
    (share/"fonts").install "CoelacanthPearlHeavy.otf"
    (share/"fonts").install "CoelacanthPearlLt.otf"
    (share/"fonts").install "CoelacanthPearlSemibd.otf"
    (share/"fonts").install "CoelacanthSemibd.otf"
    (share/"fonts").install "CoelacanthSubcapt.otf"
    (share/"fonts").install "CoelacanthSubcaptBold.otf"
    (share/"fonts").install "CoelacanthSubcaptExtraLt.otf"
    (share/"fonts").install "CoelacanthSubcaptHeavy.otf"
    (share/"fonts").install "CoelacanthSubcaptLt.otf"
    (share/"fonts").install "CoelacanthSubcaptSemibd.otf"
    (share/"fonts").install "CoelacanthSubhd.otf"
    (share/"fonts").install "CoelacanthSubhdBold.otf"
    (share/"fonts").install "CoelacanthSubhdExtraLt.otf"
    (share/"fonts").install "CoelacanthSubhdHeavy.otf"
    (share/"fonts").install "CoelacanthSubhdLt.otf"
    (share/"fonts").install "CoelacanthSubhdSemibd.otf"
  end
  test do
  end
end
