class FontRecursiveMonoNerdFont < Formula
  version "3.2.1"
  sha256 "9d6cff7ae4570f4bdd8351723214ca8323f8a99420bd5296dea2aa0b4be984d3"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Recursive.zip"
  desc "RecMono Nerd Font families (Recursive Mono)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "RecMonoCasualNerdFont-Bold.ttf"
    (share/"fonts").install "RecMonoCasualNerdFont-BoldItalic.ttf"
    (share/"fonts").install "RecMonoCasualNerdFont-Italic.ttf"
    (share/"fonts").install "RecMonoCasualNerdFont-Regular.ttf"
    (share/"fonts").install "RecMonoCasualNerdFontMono-Bold.ttf"
    (share/"fonts").install "RecMonoCasualNerdFontMono-BoldItalic.ttf"
    (share/"fonts").install "RecMonoCasualNerdFontMono-Italic.ttf"
    (share/"fonts").install "RecMonoCasualNerdFontMono-Regular.ttf"
    (share/"fonts").install "RecMonoCasualNerdFontPropo-Bold.ttf"
    (share/"fonts").install "RecMonoCasualNerdFontPropo-BoldItalic.ttf"
    (share/"fonts").install "RecMonoCasualNerdFontPropo-Italic.ttf"
    (share/"fonts").install "RecMonoCasualNerdFontPropo-Regular.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFont-Bold.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFont-BoldItalic.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFont-Italic.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFont-Regular.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFontMono-Bold.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFontMono-BoldItalic.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFontMono-Italic.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFontMono-Regular.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFontPropo-Bold.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFontPropo-BoldItalic.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFontPropo-Italic.ttf"
    (share/"fonts").install "RecMonoDuotoneNerdFontPropo-Regular.ttf"
    (share/"fonts").install "RecMonoLinearNerdFont-Bold.ttf"
    (share/"fonts").install "RecMonoLinearNerdFont-BoldItalic.ttf"
    (share/"fonts").install "RecMonoLinearNerdFont-Italic.ttf"
    (share/"fonts").install "RecMonoLinearNerdFont-Regular.ttf"
    (share/"fonts").install "RecMonoLinearNerdFontMono-Bold.ttf"
    (share/"fonts").install "RecMonoLinearNerdFontMono-BoldItalic.ttf"
    (share/"fonts").install "RecMonoLinearNerdFontMono-Italic.ttf"
    (share/"fonts").install "RecMonoLinearNerdFontMono-Regular.ttf"
    (share/"fonts").install "RecMonoLinearNerdFontPropo-Bold.ttf"
    (share/"fonts").install "RecMonoLinearNerdFontPropo-BoldItalic.ttf"
    (share/"fonts").install "RecMonoLinearNerdFontPropo-Italic.ttf"
    (share/"fonts").install "RecMonoLinearNerdFontPropo-Regular.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFont-Bold.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFont-BoldItalic.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFont-Italic.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFont-Regular.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFontMono-Bold.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFontMono-BoldItalic.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFontMono-Italic.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFontMono-Regular.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFontPropo-Bold.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFontPropo-BoldItalic.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFontPropo-Italic.ttf"
    (share/"fonts").install "RecMonoSmCasualNerdFontPropo-Regular.ttf"
  end
  # No zap stanza required

  test do
  end
end
