class FontLatinModern < Formula
  version "2.004"
  sha256 "5b0236051d3728be6616f1b274e3b910473875b5a3ef9382f0ef00384ddb161b"
  url "https://www.gust.org.pl/projects/e-foundry/latin-modern/download/lm#{version}otf.zip"
  desc "Latin Modern"
  desc "Latin Modern font family, derived from Computer Modern fonts"
  homepage "https://www.gust.org.pl/projects/e-foundry/latin-modern"
  def install
    (share/"fonts").install Dir.glob("./**/lmmono10-italic.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmono10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmono12-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmono8-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmono9-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonocaps10-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonocaps10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonolt10-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonolt10-boldoblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonolt10-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonolt10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonoltcond10-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonoltcond10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonoprop10-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonoprop10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonoproplt10-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonoproplt10-boldoblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonoproplt10-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonoproplt10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmmonoslant10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman10-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman10-bolditalic.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman10-italic.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman12-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman12-italic.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman12-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman17-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman5-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman5-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman6-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman6-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman7-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman7-italic.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman7-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman8-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman8-italic.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman8-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman9-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman9-italic.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmroman9-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromancaps10-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromancaps10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromandemi10-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromandemi10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromandunh10-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromandunh10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromanslant10-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromanslant10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromanslant12-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromanslant17-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromanslant8-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromanslant9-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmromanunsl10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans10-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans10-boldoblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans10-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans12-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans12-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans17-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans17-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans8-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans8-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans9-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsans9-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsansdemicond10-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsansdemicond10-regular.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsansquot8-bold.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsansquot8-boldoblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsansquot8-oblique.otf")[0]
    (share/"fonts").install Dir.glob("./**/lmsansquot8-regular.otf")[0]
  end
  # No zap stanza required

  test do
  end
end
