class FontPlemolJp < Formula
  desc "Japanese programming font synthesized from IBM Plex Mono and IBM Plex Sans JP"
  homepage "https://github.com/yuru7/PlemolJP"
  url "https://github.com/yuru7/PlemolJP/releases/download/v1.7.1/PlemolJP_v1.7.1.zip"
  version "1.7.1"
  sha256 "6aab0c223b60e90470d58b7bf7a1dfb4280d9a47112cefadf6d35bc92e0f534d"

  def install
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35/PlemolJP35-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP35Console/PlemolJP35Console-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJPConsole/PlemolJPConsole-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP_v1.7.1/PlemolJP/PlemolJP-Bold.ttf")[0]
  end

  test do
    assert_path_exists share/"fonts"
  end
end
