class FontUrbanist < Formula
  version "1.321"
  sha256 "43b9c601884e3d348016444d34c5d55ac3381d18fdbe9644432be50305fa54c3"
  url "https://github.com/coreyhu/Urbanist/releases/download/v#{version}/Urbanist-fonts.zip"
  desc "Urbanist"
  homepage "https://github.com/coreyhu/Urbanist"
  def install
    parent = File.dirname(Dir.pwd) != (ENV['HOMEBREW_TEMP'] || '/tmp') ?  '../' : ''
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-Black.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-BlackItalic.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-Bold.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-BoldItalic.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-ExtraBold.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-ExtraBoldItalic.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-ExtraLight.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-ExtraLightItalic.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-Italic.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-Light.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-LightItalic.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-Medium.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-MediumItalic.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-Regular.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-SemiBold.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-SemiBoldItalic.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-Thin.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/otf/Urbanist-ThinItalic.otf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-Black.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-BlackItalic.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-Bold.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-BoldItalic.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-ExtraBold.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-ExtraBoldItalic.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-ExtraLight.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-ExtraLightItalic.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-Italic.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-Light.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-LightItalic.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-Medium.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-MediumItalic.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-Regular.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-SemiBold.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-SemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-Thin.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/ttf/Urbanist-ThinItalic.ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/variable/Urbanist-Italic[wght].ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/variable/Urbanist[ital,wght].ttf"
    (share/"fonts").install "#{parent}Urbanist-fonts/fonts/variable/Urbanist[wght].ttf"
  end
  test do
  end
end
