class FontNotoSansLao < Formula
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansLao-unhinted.zip", verified: "noto-website-2.storage.googleapis.com/"
  desc "Noto Sans Lao"
  homepage "https://www.google.com/get/noto/#sans-laoo"
  def install
    (share/"fonts").install Dir.glob("./**/NotoSansLao-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLao-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansLaoUI-Thin.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
