class FontNotoSansSinhala < Formula
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSinhala-unhinted.zip", verified: "noto-website-2.storage.googleapis.com/"
  desc "Noto Sans Sinhala"
  homepage "https://www.google.com/get/noto/#sans-sinh"
  def install
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhala-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansSinhalaUI-Thin.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
