class FontNotoSansArabic < Formula
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip", verified: "noto-website-2.storage.googleapis.com/"
  desc "Noto Sans Arabic"
  homepage "https://www.google.com/get/noto/#sans-arab"
  def install
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabic-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansArabicUI-Thin.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
