class FontJetbrainsMono < Formula
  version "2.001"
  sha256 "d9176856e982ca16f4ee24a1021a62b51cea43575f3c6aa1910d4cdf6b695ade"
  url "https://github.com/JetBrains/JetBrainsMono/releases/download/v#{version}/JetBrains.Mono.#{version}.zip"
  desc "JetBrains Mono"
  homepage "https://www.jetbrains.com/lp/mono"
  def install
    parent = File.dirname(Dir.pwd) != (ENV['HOMEBREW_TEMP'] || '/tmp') ?  '../' : ''
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-Bold-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-Bold.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-ExtraBold-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-ExtraBold.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-ExtraLight-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-ExtraLight.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-Light-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-Light.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-Medium-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-Medium.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-Regular.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-SemiLight-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/JetBrainsMono-SemiLight.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-Bold-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-Bold.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-ExtraBold-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-ExtraBold.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-ExtraLight-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-ExtraLight.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-Light-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-Light.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-Medium-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-Medium.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-Regular.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-SemiLight-Italic.ttf"
    (share/"fonts").install "#{parent}JetBrains Mono #{version}/ttf/No ligatures/JetBrainsMonoNL-SemiLight.ttf"
  end
  test do
  end
end
