class FontPlemolJpNfj < Formula
  version "1.3.0"
  sha256 "750e9db9ca227f2deabaf93efa4e2ee3bc07c469f8c5e5bae56d335874bb427c"
  url "https://github.com/yuru7/PlemolJP/releases/download/v#{version}/PlemolJP_NFJ_v#{version}.zip"
  desc "PlemolJP NF"
  desc "Japanese programming font synthesized from IBM Plex Mono and IBM Plex Sans JP"
  homepage "https://github.com/yuru7/PlemolJP"
  def install
    parent = File.dirname(Dir.pwd) != (ENV['HOMEBREW_TEMP'] || '/tmp') ?  '../' : ''
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Bold.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-BoldItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-ExtraLight.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-ExtraLightItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Italic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Light.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-LightItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Medium.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-MediumItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Regular.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-SemiBold.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-SemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Text.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-TextItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-Thin.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJPConsole_NFJ/PlemolJPConsoleNFJ-ThinItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Bold.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-BoldItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-ExtraLight.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-ExtraLightItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Italic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Light.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-LightItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Medium.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-MediumItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Regular.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-SemiBold.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-SemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Text.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-TextItalic.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-Thin.ttf"
    (share/"fonts").install "#{parent}PlemolJP_NFJ_v#{version}/PlemolJP35Console_NFJ/PlemolJP35ConsoleNFJ-ThinItalic.ttf"
  end
  test do
  end
end
