class FontMontserrat < Formula
  version "7.200"
  sha256 "81b2c8f0148d6acf62b59f78869ad7eff28adcd9d19cddec4777d482df5dcd71"
  url "https://github.com/JulietaUla/Montserrat/archive/v#{version}.zip"
  desc "Montserrat"
  homepage "https://github.com/JulietaUla/Montserrat"
  def install
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-Black.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-BlackItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-Bold.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-BoldItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-ExtraBold.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-ExtraBoldItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-ExtraLight.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-ExtraLightItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-Italic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-Light.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-LightItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-Medium.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-MediumItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-Regular.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-SemiBold.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-SemiBoldItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-Thin.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserrat-ThinItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-Black.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-BlackItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-Bold.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-BoldItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-ExtraBold.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-ExtraBoldItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-ExtraLight.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-ExtraLightItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-Italic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-Light.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-LightItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-Medium.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-MediumItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-Regular.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-SemiBold.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-SemiBoldItalic.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-Thin.otf"
    (share/"fonts").install "../Montserrat-#{version}/fonts/otfMontserratAlternates-ThinItalic.otf"
  end
  test do
  end
end
