class FontMonaSans < Formula
  version "1.0"
  sha256 "605cab19df336c927d49af180cd1cb7037f7e1f7a203075629cf5d23c096dd06"
  url "https://github.com/github/mona-sans/releases/download/v#{version}/Mona.Sans.#{version}.zip"
  desc "Mona-Sans"
  desc "Mona Sans, a variable font from GitHub"
  homepage "https://github.com/github/mona-sans"
  def install
    parent = File.dirname(Dir.pwd) != (ENV['HOMEBREW_TEMP'] || '/tmp') ?  '../' : ''
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-Black.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-BlackItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-BlackNarrow.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-BlackNarrowItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-BlackWide.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-BlackWideItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-Bold.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-BoldItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-BoldNarrow.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-BoldNarrowItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-BoldWide.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-BoldWideItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-ExtraBold.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-ExtraBoldItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-ExtraBoldNarrow.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-ExtraBoldNarrowItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-ExtraBoldWide.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-ExtraBoldWideItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-Light.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-LightItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-LightNarrow.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-LightNarrowItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-LightWide.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-LightWideItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-Medium.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-MediumItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-MediumNarrow.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-MediumNarrowItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-MediumWide.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-MediumWideItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-Regular.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-RegularItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-RegularNarrow.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-RegularNarrowItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-RegularWide.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-RegularWideItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-SemiBold.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-SemiBoldItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-SemiBoldNarrow.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-SemiBoldNarrowItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-SemiBoldWide.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-SemiBoldWideItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-UltraLight.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-UltraLightItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-UltraLightNarrow.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-UltraLightNarrowItalic.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-UltraLightWide.otf"
    (share/"fonts").install "#{parent}Mona Sans/OTF/Mona-Sans-UltraLightWideItalic.otf"
  end
  test do
  end
end
