class FontIosevkaSlab < Formula
  version "2.2.0"
  sha256 "b4a2458014711ab874298ac2669e09a6a9637b0cf56f3828d5defe11e805cda0"
  url "https://github.com/be5invis/Iosevka/releases/download/v#{version}/ttc-iosevka-slab-#{version}.zip"
  desc "Iosevka Slab"
  homepage "https://github.com/be5invis/Iosevka/"
  def install
    (share/"fonts").install "iosevka-slab-bold.ttc"
    (share/"fonts").install "iosevka-slab-bolditalic.ttc"
    (share/"fonts").install "iosevka-slab-boldoblique.ttc"
    (share/"fonts").install "iosevka-slab-extrabold.ttc"
    (share/"fonts").install "iosevka-slab-extrabolditalic.ttc"
    (share/"fonts").install "iosevka-slab-extraboldoblique.ttc"
    (share/"fonts").install "iosevka-slab-extralight.ttc"
    (share/"fonts").install "iosevka-slab-extralightitalic.ttc"
    (share/"fonts").install "iosevka-slab-extralightoblique.ttc"
    (share/"fonts").install "iosevka-slab-heavy.ttc"
    (share/"fonts").install "iosevka-slab-heavyitalic.ttc"
    (share/"fonts").install "iosevka-slab-heavyoblique.ttc"
    (share/"fonts").install "iosevka-slab-italic.ttc"
    (share/"fonts").install "iosevka-slab-light.ttc"
    (share/"fonts").install "iosevka-slab-lightitalic.ttc"
    (share/"fonts").install "iosevka-slab-lightoblique.ttc"
    (share/"fonts").install "iosevka-slab-medium.ttc"
    (share/"fonts").install "iosevka-slab-mediumitalic.ttc"
    (share/"fonts").install "iosevka-slab-mediumoblique.ttc"
    (share/"fonts").install "iosevka-slab-oblique.ttc"
    (share/"fonts").install "iosevka-slab-regular.ttc"
    (share/"fonts").install "iosevka-slab-semibold.ttc"
    (share/"fonts").install "iosevka-slab-semibolditalic.ttc"
    (share/"fonts").install "iosevka-slab-semiboldoblique.ttc"
    (share/"fonts").install "iosevka-slab-thin.ttc"
    (share/"fonts").install "iosevka-slab-thinitalic.ttc"
    (share/"fonts").install "iosevka-slab-thinoblique.ttc"
  end
  test do
  end
end
