class FontNotoSansDevanagari < Formula
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansDevanagari-unhinted.zip", verified: "noto-website-2.storage.googleapis.com/"
  desc "Noto Sans Devanagari"
  homepage "https://www.google.com/get/noto/#sans-deva"
  def install
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagari-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansDevanagariUI-Thin.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
