class FontHubotSans < Formula
  version "1.0"
  sha256 "f6dc82db6517d394c8930f1c45cdad97215b8e44defd3b1d712377e08c86e1dc"
  url "https://github.com/github/hubot-sans/releases/download/v#{version}/Hubot.Sans.#{version}.zip"
  desc "Hubot-Sans"
  desc "Hubot Sans, a variable font from GitHub"
  homepage "https://github.com/github/hubot-sans"
  def install
    parent = File.dirname(Dir.pwd) != (ENV['HOMEBREW_TEMP'] || '/tmp') ?  '../' : ''
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-Black.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BlackItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BlackNarrow.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BlackNarrowItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BlackSemi.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BlackSemiItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BlackWide.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BlackWideItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-Bold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BoldNarrow.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BoldNarrowItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BoldSemi.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BoldSemiItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BoldWide.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-BoldWideItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraBold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraBoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraBoldNarrow.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraBoldNarrowItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraBoldSemi.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraBoldSemiItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraBoldWide.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraBoldWideItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraLight.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraLightItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraLightNarrow.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraLightNarrowItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraLightSemi.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraLightSemiItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraLightWide.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-ExtraLightWideItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-Light.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-LightItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-LightNarrow.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-LightNarrowItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-LightSemi.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-LightSemiItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-LightWide.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-LightWideItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-Medium.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-MediumItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-MediumNarrow.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-MediumNarrowItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-MediumSemi.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-MediumSemiItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-MediumWide.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-MediumWideItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-Regular.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-RegularItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-RegularNarrow.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-RegularNarrowItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-RegularSemi.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-RegularSemiItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-RegularWide.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-RegularWideItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-SemiBold.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-SemiBoldItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-SemiBoldNarrow.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-SemiBoldNarrowItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-SemiBoldSemi.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-SemiBoldSemiItalic.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-SemiBoldWide.otf"
    (share/"fonts").install "#{parent}Hubot Sans/OTF/Hubot-Sans-SemiBoldWideItalic.otf"
  end
  test do
  end
end
