class FontCaskaydiaCoveNerdFont < Formula
  version "3.2.0"
  sha256 "debfc4ba14049857c3742963ac2665ea8ff6db8ab7c5f8c436c69079ae04b9c2"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/CascadiaCode.zip"
  desc "CaskaydiaCove Nerd Font (Cascadia Code)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "CaskaydiaCoveNerdFont-Bold.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-BoldItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-ExtraLight.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-ExtraLightItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-Italic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-Light.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-LightItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-Regular.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-SemiBold.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-SemiBoldItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-SemiLight.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFont-SemiLightItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-Bold.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-BoldItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-ExtraLight.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-ExtraLightItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-Italic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-Light.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-LightItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-Regular.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-SemiBold.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-SemiBoldItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-SemiLight.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontMono-SemiLightItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-Bold.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-BoldItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-ExtraLight.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-ExtraLightItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-Italic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-Light.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-LightItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-Regular.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-SemiBold.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-SemiBoldItalic.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-SemiLight.ttf"
    (share/"fonts").install "CaskaydiaCoveNerdFontPropo-SemiLightItalic.ttf"
  end
  # No zap stanza required

  test do
  end
end
