class FontNotoSerifDisplay < Formula
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifDisplay-unhinted.zip", verified: "noto-website-2.storage.googleapis.com/"
  desc "Noto Serif Display"
  homepage "https://www.google.com/get/noto/#serif-lgc-display"
  def install
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-BlackItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedBlackItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedExtraBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedMediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedSemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-CondensedThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedBlackItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedExtraBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedMediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedSemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraCondensedThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedBlackItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedExtraBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedMediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedSemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-SemiCondensedThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSerifDisplay-ThinItalic.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
