class FontZedMono < Formula
  version "1.2.0"
  sha256 "eb673b39528927d21c0b12eaf05e50babc486bc99e724b55c88e529a5dae76c9"
  url "https://github.com/zed-industries/zed-fonts/releases/download/#{version}/zed-mono-#{version}.zip"
  desc "Zed Mono"
  desc "Quasi-proportional monospace font based on Iosevka"
  homepage "https://github.com/zed-industries/zed-fonts"
  def install
    (share/"fonts").install "zed-mono-bold.ttf"
    (share/"fonts").install "zed-mono-bolditalic.ttf"
    (share/"fonts").install "zed-mono-boldoblique.ttf"
    (share/"fonts").install "zed-mono-extended.ttf"
    (share/"fonts").install "zed-mono-extendedbold.ttf"
    (share/"fonts").install "zed-mono-extendedbolditalic.ttf"
    (share/"fonts").install "zed-mono-extendedboldoblique.ttf"
    (share/"fonts").install "zed-mono-extendedextrabold.ttf"
    (share/"fonts").install "zed-mono-extendedextrabolditalic.ttf"
    (share/"fonts").install "zed-mono-extendedextraboldoblique.ttf"
    (share/"fonts").install "zed-mono-extendedextralight.ttf"
    (share/"fonts").install "zed-mono-extendedextralightitalic.ttf"
    (share/"fonts").install "zed-mono-extendedextralightoblique.ttf"
    (share/"fonts").install "zed-mono-extendedheavy.ttf"
    (share/"fonts").install "zed-mono-extendedheavyitalic.ttf"
    (share/"fonts").install "zed-mono-extendedheavyoblique.ttf"
    (share/"fonts").install "zed-mono-extendeditalic.ttf"
    (share/"fonts").install "zed-mono-extendedlight.ttf"
    (share/"fonts").install "zed-mono-extendedlightitalic.ttf"
    (share/"fonts").install "zed-mono-extendedlightoblique.ttf"
    (share/"fonts").install "zed-mono-extendedmedium.ttf"
    (share/"fonts").install "zed-mono-extendedmediumitalic.ttf"
    (share/"fonts").install "zed-mono-extendedmediumoblique.ttf"
    (share/"fonts").install "zed-mono-extendedoblique.ttf"
    (share/"fonts").install "zed-mono-extendedsemibold.ttf"
    (share/"fonts").install "zed-mono-extendedsemibolditalic.ttf"
    (share/"fonts").install "zed-mono-extendedsemiboldoblique.ttf"
    (share/"fonts").install "zed-mono-extendedthin.ttf"
    (share/"fonts").install "zed-mono-extendedthinitalic.ttf"
    (share/"fonts").install "zed-mono-extendedthinoblique.ttf"
    (share/"fonts").install "zed-mono-extrabold.ttf"
    (share/"fonts").install "zed-mono-extrabolditalic.ttf"
    (share/"fonts").install "zed-mono-extraboldoblique.ttf"
    (share/"fonts").install "zed-mono-extralight.ttf"
    (share/"fonts").install "zed-mono-extralightitalic.ttf"
    (share/"fonts").install "zed-mono-extralightoblique.ttf"
    (share/"fonts").install "zed-mono-heavy.ttf"
    (share/"fonts").install "zed-mono-heavyitalic.ttf"
    (share/"fonts").install "zed-mono-heavyoblique.ttf"
    (share/"fonts").install "zed-mono-italic.ttf"
    (share/"fonts").install "zed-mono-light.ttf"
    (share/"fonts").install "zed-mono-lightitalic.ttf"
    (share/"fonts").install "zed-mono-lightoblique.ttf"
    (share/"fonts").install "zed-mono-medium.ttf"
    (share/"fonts").install "zed-mono-mediumitalic.ttf"
    (share/"fonts").install "zed-mono-mediumoblique.ttf"
    (share/"fonts").install "zed-mono-oblique.ttf"
    (share/"fonts").install "zed-mono-regular.ttf"
    (share/"fonts").install "zed-mono-semibold.ttf"
    (share/"fonts").install "zed-mono-semibolditalic.ttf"
    (share/"fonts").install "zed-mono-semiboldoblique.ttf"
    (share/"fonts").install "zed-mono-thin.ttf"
    (share/"fonts").install "zed-mono-thinitalic.ttf"
    (share/"fonts").install "zed-mono-thinoblique.ttf"
  end
  # No zap stanza required

  test do
  end
end
