class FontPlemolJp < Formula
  desc "Plemoljp font"
  homepage "https://github.com/yuru7/PlemolJP"
  url "https://github.com/yuru7/PlemolJP/releases/download/v2.0.0/PlemolJP_v2.0.0.zip"
  version "2.0.0"
  sha256 "d5f98cc23dec832c63ce64904e6deec0da40d9ea97a12a9ca2510f39fa8396d7"

  def install
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP/PlemolJP-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35/PlemolJP35-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJP35Console/PlemolJP35Console-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-Text.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-TextItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/PlemolJPConsole/PlemolJPConsole-ThinItalic.ttf")[0]
  end

  test do
    assert_path_exists share/"fonts"
  end
end
