class FontOverpassNerdFont < Formula
  version "2.1.0"
  sha256 "b5f7522a2e884562cfca4c32fa708d537b884efb5d055ad617a3b503d9f842f7"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Overpass.zip"
  desc "Overpass Nerd Font (Overpass)"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "Overpass Mono Bold Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Mono Bold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Mono SemiBold Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Mono SemiBold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Mono Regular Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Mono Regular Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Mono Light Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Mono Light Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Bold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Bold Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Heavy Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Heavy Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass ExtraBold Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass ExtraBold Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass SemiBold Nerd Font Complete.otf"
    (share/"fonts").install "Overpass SemiBold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Bold Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Bold Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass ExtraLight Nerd Font Complete.otf"
    (share/"fonts").install "Overpass ExtraLight Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass SemiBold Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass SemiBold Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass ExtraLight Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass ExtraLight Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Regular Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Regular Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Heavy Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Heavy Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Thin Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Thin Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Thin Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Thin Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass ExtraBold Nerd Font Complete.otf"
    (share/"fonts").install "Overpass ExtraBold Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Italic Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Light Nerd Font Complete Mono.otf"
    (share/"fonts").install "Overpass Light Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Light Italic Nerd Font Complete.otf"
    (share/"fonts").install "Overpass Light Italic Nerd Font Complete Mono.otf"
  end
  test do
  end
end
