class FontVictorMonoNerdFont < Formula
  version "3.2.1"
  sha256 "987c8697510a9819db98b828da599eeedf3e00242d4a8cc8d762b19fab227183"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/VictorMono.zip"
  desc "VictorMono Nerd Font (Victor Mono)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-BoldOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-ExtraLightOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-LightOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-MediumOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-Oblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-SemiBoldOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFont-ThinOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-BoldOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-ExtraLightOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-LightOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-MediumOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-Oblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-SemiBoldOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontMono-ThinOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-BoldOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-ExtraLightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-ExtraLightOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-LightItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-LightOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-MediumItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-MediumOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-Oblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-SemiBoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-SemiBoldOblique.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-ThinItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/VictorMonoNerdFontPropo-ThinOblique.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
