class FontMesloLgNerdFont < Formula
  version "3.2.1"
  sha256 "c54d6ad2eabaaac59a436b9d37de62f2f8407516e85a31023313f6e91ca12694"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/Meslo.zip"
  desc "MesloLG Nerd Font families (Meslo LG)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFont-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFont-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFont-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFont-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFontMono-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFontMono-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFontMono-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFontMono-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFontPropo-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFontPropo-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFontPropo-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLDZNerdFontPropo-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFont-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFont-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFont-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFont-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFontMono-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFontMono-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFontMono-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFontMono-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFontPropo-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFontPropo-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFontPropo-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGLNerdFontPropo-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFont-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFont-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFont-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFont-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFontMono-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFontMono-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFontMono-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFontMono-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFontPropo-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFontPropo-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFontPropo-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMDZNerdFontPropo-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFont-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFont-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFont-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFont-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFontMono-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFontMono-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFontMono-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFontMono-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFontPropo-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFontPropo-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFontPropo-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGMNerdFontPropo-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFont-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFont-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFont-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFont-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFontMono-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFontMono-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFontMono-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFontMono-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFontPropo-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFontPropo-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFontPropo-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSDZNerdFontPropo-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFont-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFont-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFont-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFont-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFontMono-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFontMono-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFontMono-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFontMono-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFontPropo-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFontPropo-BoldItalic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFontPropo-Italic.ttf")[0]
    (share/"fonts").install Dir.glob("./**/MesloLGSNerdFontPropo-Regular.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
