class FontElstobd < Formula
  version "1.015"
  sha256 "4cd99be64bd5086e806469ee7c8af5f515d667ad4c5eaaa1bd3e63f38bd23128"
  url "https://github.com/psb1558/Elstob-font/releases/download/v#{version}/Elstob_v#{version.to_s.gsub(".", "_")}.zip"
  desc "ElstobD"
  homepage "https://github.com/psb1558/Elstob-font"
  def install
    parent = File.dirname(Dir.pwd) != (ENV['HOMEBREW_TEMP'] || '/tmp') ?  '../' : ''
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-10pt.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-10ptBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-10ptBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-10ptItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-10ptMedium.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-10ptMediumItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-10ptSemiBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-10ptSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-14pt.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-14ptBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-14ptBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-14ptItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-14ptMedium.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-14ptMediumItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-14ptSemiBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-14ptSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-18pt.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-18ptBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-18ptBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-18ptExtraBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-18ptExtraBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-18ptItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-18ptMedium.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-18ptMediumItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-18ptSemiBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-18ptSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-8pt.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-8ptBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-8ptBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-8ptItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-8ptMedium.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-8ptMediumItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-8ptSemiBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-8ptSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-Bold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-BoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-ExtraBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-ExtraBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-ExtraLight.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-ExtraLightItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-Italic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-Light.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-LightItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-Medium.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-MediumItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-Regular.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-SemiBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font/desktop/ElstobD-SemiBoldItalic.ttf"
  end
  test do
  end
end
