class FontFiraCodeNerdFont < Formula
  version "2.2.1"
  sha256 "63410350230ad9c1873df4b1e154066d809cff2490e5bbc440f05d7967ee8e2f"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/FiraCode.zip"
  desc "FiraCode Nerd Font (Fira Code)"
  homepage "https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode"
  def install
    (share/"fonts").install "Fira Code Bold Nerd Font Complete Mono Windows Compatible.ttf"
    (share/"fonts").install "Fira Code Bold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Fira Code Bold Nerd Font Complete Windows Compatible.ttf"
    (share/"fonts").install "Fira Code Bold Nerd Font Complete.ttf"
    (share/"fonts").install "Fira Code Light Nerd Font Complete Mono Windows Compatible.ttf"
    (share/"fonts").install "Fira Code Light Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Fira Code Light Nerd Font Complete Windows Compatible.ttf"
    (share/"fonts").install "Fira Code Light Nerd Font Complete.ttf"
    (share/"fonts").install "Fira Code Medium Nerd Font Complete Mono Windows Compatible.ttf"
    (share/"fonts").install "Fira Code Medium Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Fira Code Medium Nerd Font Complete Windows Compatible.ttf"
    (share/"fonts").install "Fira Code Medium Nerd Font Complete.ttf"
    (share/"fonts").install "Fira Code Regular Nerd Font Complete Mono Windows Compatible.ttf"
    (share/"fonts").install "Fira Code Regular Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Fira Code Regular Nerd Font Complete Windows Compatible.ttf"
    (share/"fonts").install "Fira Code Regular Nerd Font Complete.ttf"
    (share/"fonts").install "Fira Code Retina Nerd Font Complete Mono Windows Compatible.ttf"
    (share/"fonts").install "Fira Code Retina Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Fira Code Retina Nerd Font Complete Windows Compatible.ttf"
    (share/"fonts").install "Fira Code Retina Nerd Font Complete.ttf"
    (share/"fonts").install "Fira Code SemiBold Nerd Font Complete Mono Windows Compatible.ttf"
    (share/"fonts").install "Fira Code SemiBold Nerd Font Complete Mono.ttf"
    (share/"fonts").install "Fira Code SemiBold Nerd Font Complete Windows Compatible.ttf"
    (share/"fonts").install "Fira Code SemiBold Nerd Font Complete.ttf"
  end
  test do
  end
end
