class FontFiraSans < Formula
  version "4.202"
  sha256 "d86269657387f144d77ba12011124f30f423f70672e1576dc16f918bb16ddfe4"
  url "https://github.com/mozilla/Fira/archive/#{version}.tar.gz", verified: "github.com/mozilla/Fira/"
  desc "Fira Sans"
  homepage "https://mozilla.github.io/Fira/"
  def install
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-BoldItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Bold.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-BookItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Book.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-BoldItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Bold.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-BookItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Book.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-EightItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Eight.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-ExtraboldItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-ExtraBold.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-ExtraLightItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-ExtraLight.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-FourItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Four.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-HairItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Hair.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-HeavyItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Heavy.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Italic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-LightItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Light.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-MediumItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Medium.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Regular.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-SemiboldItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-SemiBold.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-ThinItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Thin.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-TwoItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Two.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-UltraItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-UltraLightItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-UltraLight.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSansCondensed-Ultra.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-EightItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Eight.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-ExtraBoldItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-ExtraBold.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-ExtraLightItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-ExtraLight.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-FourItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Four.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-HairItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Hair.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-HeavyItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Heavy.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Italic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-LightItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Light.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-MediumItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Medium.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Regular.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-SemiBoldItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-SemiBold.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-ThinItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Thin.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-TwoItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Two.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-UltraItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-UltraLightItalic.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-UltraLight.otf")[0]
    (share/"fonts").install Dir.glob("Fira-#{version}/otf/**/FiraSans-Ultra.otf")[0]
  end
  # No zap stanza required

  test do
  end
end
