class FontAlegreyaSans < Formula
  version "2.008"
  sha256 "ff8d1290eae47df0d1f710083690aa7f46508acfb2f1d6bce04b1355ac56dbab"
  url "https://github.com/huertatipografica/Alegreya-Sans/archive/v#{version}.zip"
  desc "Alegreya-Sans"
  homepage "https://github.com/huertatipografica/Alegreya-Sans"
  def install
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-Black.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-BlackItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-Bold.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-BoldItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-ExtraBold.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-ExtraBoldItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-Italic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-Light.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-LightItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-Medium.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-MediumItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-Regular.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-Thin.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSans-ThinItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-Black.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-BlackItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-Bold.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-BoldItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-ExtraBold.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-ExtraBoldItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-Italic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-Light.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-LightItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-Medium.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-MediumItalic.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-Regular.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-Thin.otf"
    (share/"fonts").install "../Alegreya-Sans-#{version}/fonts/otfAlegreyaSansSC-ThinItalic.otf"
  end
  test do
  end
end
