class FontCormorant < Formula
  version "3.601"
  sha256 "59997266f48655f7365c0de16d2c4ea6e92a7d8f549fd97c95f1cbe307901e1e"
  url "https://github.com/CatharsisFonts/Cormorant/releases/download/v#{version}/Cormorant_Install_v#{version}.zip"
  desc "Cormorant"
  homepage "https://github.com/CatharsisFonts/Cormorant/"
  def install
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorant-Bold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorant-BoldItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorant-Italic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorant-Light.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorant-LightItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorant-Medium.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorant-MediumItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorant-Regular.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorant-SemiBold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorant-SemiBoldItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantGaramond-Bold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantGaramond-BoldItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantGaramond-Italic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantGaramond-Light.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantGaramond-LightItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantGaramond-Medium.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantGaramond-MediumItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantGaramond-Regular.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantGaramond-SemiBold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantGaramond-SemiBoldItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantInfant-Bold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantInfant-BoldItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantInfant-Italic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantInfant-Light.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantInfant-LightItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantInfant-Medium.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantInfant-MediumItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantInfant-Regular.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantInfant-SemiBold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantInfant-SemiBoldItalic.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantSC-Bold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantSC-Light.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantSC-Medium.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantSC-Regular.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantSC-SemiBold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantUnicase-Bold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantUnicase-Light.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantUnicase-Medium.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantUnicase-Regular.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantUnicase-SemiBold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantUpright-Bold.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantUpright-Light.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantUpright-Medium.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantUpright-Regular.ttf"
    (share/"fonts").install "../Cormorant_Install_v#{version}/1. TrueType Font FilesCormorantUpright-SemiBold.ttf"
  end
  test do
  end
end
