class FontNotoSansMyanmar < Formula
  head "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMyanmar-unhinted.zip", verified: "noto-website-2.storage.googleapis.com/"
  desc "Noto Sans Myanmar"
  homepage "https://www.google.com/get/noto/#sans-mymr"
  def install
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmar-Thin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-Black.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-Bold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-Condensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-CondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-CondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-CondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-CondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-CondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-CondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-CondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-CondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-ExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-Light.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-Medium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-Regular.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-SemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-SemiCondensed.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-SemiCondensedBlack.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-SemiCondensedBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-SemiCondensedExtraBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-SemiCondensedExtraLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-SemiCondensedLight.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-SemiCondensedMedium.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-SemiCondensedSemiBold.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-SemiCondensedThin.ttf")[0]
    (share/"fonts").install Dir.glob("./**/NotoSansMyanmarUI-Thin.ttf")[0]
  end
  # No zap stanza required

  test do
  end
end
