class FontIosevkaTermSlabNerdFont < Formula
  version "3.2.1"
  sha256 "c696406e606d677c2e1a5771c097c925e533e9037eb10063521a177cbfc4d304"
  url "https://github.com/ryanoasis/nerd-fonts/releases/download/v#{version}/IosevkaTermSlab.zip"
  desc "IosevkaTermSlab Nerd Font (Iosevka Term Slab)"
  desc "Developer targeted fonts with a high number of glyphs"
  homepage "https://github.com/ryanoasis/nerd-fonts"
  def install
    (share/"fonts").install "IosevkaTermSlabNerdFont-Bold.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-BoldItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-BoldOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-ExtraBold.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-ExtraBoldItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-ExtraBoldOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-Italic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-Light.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-LightItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-LightOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-Medium.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-MediumItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-MediumOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-Oblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFont-Regular.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-Bold.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-BoldItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-BoldOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-ExtraBold.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-ExtraBoldItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-ExtraBoldOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-Italic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-Light.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-LightItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-LightOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-Medium.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-MediumItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-MediumOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-Oblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontMono-Regular.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-Bold.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-BoldItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-BoldOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-ExtraBold.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-ExtraBoldItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-ExtraBoldOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-Italic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-Light.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-LightItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-LightOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-Medium.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-MediumItalic.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-MediumOblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-Oblique.ttf"
    (share/"fonts").install "IosevkaTermSlabNerdFontPropo-Regular.ttf"
  end
  # No zap stanza required

  test do
  end
end
