class FontElstobd < Formula
  version "1.003"
  sha256 "b26178abb6f929b7971286e4e5712ade19aafc6d5081786db19f13a79e436806"
  url "https://github.com/psb1558/Elstob-font/releases/download/v#{version}/Elstob_v#{version.to_s.gsub(".", "_")}_desktop.zip"
  desc "ElstobD"
  homepage "https://github.com/psb1558/Elstob-font"
  def install
    parent = File.dirname(Dir.pwd) != (ENV['HOMEBREW_TEMP'] || '/tmp') ?  '../' : ''
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-10pt.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-10ptBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-10ptBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-10ptItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-10ptMedium.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-10ptMediumItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-10ptSemiBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-10ptSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-14pt.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-14ptBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-14ptBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-14ptItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-14ptMedium.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-14ptMediumItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-14ptSemiBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-14ptSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-18pt.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-18ptBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-18ptBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-18ptExtraBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-18ptExtraBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-18ptItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-18ptMedium.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-18ptMediumItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-18ptSemiBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-18ptSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-8pt.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-8ptBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-8ptBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-8ptItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-8ptMedium.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-8ptMediumItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-8ptSemiBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-8ptSemiBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-Bold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-BoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-ExtraBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-ExtraBoldItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-ExtraLight.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-ExtraLightItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-Italic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-Light.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-LightItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-Medium.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-MediumItalic.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-Regular.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-SemiBold.ttf"
    (share/"fonts").install "#{parent}Elstob_font_desktop/ttf/ElstobD-SemiBoldItalic.ttf"
  end
  test do
  end
end
